language: java
install: true
service:
  - docker

jdk:
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: build
      script: ./gradlew build -x test && docker build -t webrato . && docker tag webrato kentio/webrato:feature && echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin && docker push kentio/webrato:feature
      
stages:
  - build