version: '3'
services:
  webrato:
    image: "kentio/webrato:feature"
    depends_on:
      - db
    environment:
      - DB_USER=myuser
      - DB_PASSWORD
    ports:
      - "8080:8080"
    restart: on-failure

  db:
    #image: "kentio/webrato-mysql:latest"
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
